name: publish

on:
  pull_request:
    types:
      - closed

jobs:
  publish-to-crates:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish release
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}